### PR TITLE
Config source

### PR DESCRIPTION
**Pull request by aharonha**
Reasoning: the interface of entries is `Mono<List<FetchResponse>>` and scalecube does not support 2 layers of generics.

### CODE REVIEW

**Comment by dmytro-lazebnyi** [comment]
@aharonha 
What does it mean `scalecube does not support 2 layers of generics`?

**Comment by aharonha** [comment]
@dmytro-lazebnyi this method from client-sdk (`io.scalecube.services.gateway.clientsdk.Reflect`): 
``` java  /**
   * extract parameterized return value of a method.
   *
   * @param method to extract type from.
   * @return the generic type of the return value or object.
   */
  private static Class<?> parameterizedReturnType(Method method) {
    Type type = method.getGenericReturnType();
    if (type instanceof ParameterizedType) {
      try {
        return Class.forName(
            (((ParameterizedType) type).getActualTypeArguments()[0]).getTypeName());
      } catch (ClassNotFoundException e) {
        return Object.class;
      }
    } else {
      return Object.class;
    }
  } 
```
The first generic level is covered here (`Mono<T>`) but no more (e.g. `Mono<List<Response>>`)

**Comment by dmytro-lazebnyi** [comment]
@aharonha 
This method is not a part of `configuration-service` implementation.
This problem should be fixed on the `scalecube-services` (and `client-sdk`) side.

I think it is not a good idea to change public API of `configuration-service` just to have a workaround for *technical issue* of `client-sdk` library.

**Comment by aharonha** [comment]
@dmytro-lazebnyi I agree that we should fix the `client-sdk` and `scalecube-services`. 
But this change is also required.

**Comment by dmytro-lazebnyi** [comment]
> But this change is also required.

Why? It is required by business needs to have two similar API?

**Comment by dmytro-lazebnyi** [comment]
The underlying issue was fixed in https://github.com/scalecube/scalecube-services/pull/550.
Let's close this PR.

**Pull request closed without merging**
